### ISSUE TITLE
[Android] Play store request new permission to this plugin used apps

### ISSUE THREAD

**Issue by mustafa-707** [ravitejaavv/store_checker#13]
Hello , 

 i would to ask if this package need to use this two permissions `QUERY_ALL_PACKAGES` and `REQUEST_INSTALL_PACKAGES`

if yes , i guess it should be added to the package help as additional info.

and if no , to investigate more about the reason for requesting this permissions 

<img width="421" alt="Screen Shot 2023-04-12 at 1 09 19 PM" src="https://user-images.githubusercontent.com/74349843/231426763-c64fc07f-d56f-4ff0-be82-610243d382b6.png">

**Comment by ravitejaavv** [comment]
Hi @mustafa-707 

This package doesn't require any permissions. 
You can check it under https://github.com/ravitejaavv/store_checker/blob/master/android/src/main/AndroidManifest.xml

But i can help you on this. Just check merged manifest to see where these permissions are coming from
/build/app/intermediates/merged_manifests directory

Also check other packages 
For example:
https://github.com/crazecoder/open_file/issues/204
