### ISSUE TITLE
arm64-Check simulator 

### ISSUE THREAD

**Issue by Menaitech** [ravitejaavv/store_checker#19]
Dears 

the function which used to  check  if app is running on simulator has an error 

please change code to following code 

 private func isSimulator() -> Bool {
        //Check architecture
      // #if arch(i386) || arch(x86_64) || arch(arm64)    // this  code is no  correct  
        #if targetEnvironment(simulator)   // this  code is correct  
        return true
        #else
        return false
        #endif
    }

Regards

**Comment by ravitejaavv** [comment]
Same has been updated in 1.4.0 version. Kindly check it
