### ISSUE TITLE
HUAWEI APPGALLERY

### ISSUE THREAD

**Issue by viperciyes** [ravitejaavv/store_checker#3]
can this detect if the app is installed from HUAWEI AppGallery?

**Comment by ravitejaavv** [comment]
> can this detect if the app is installed from HUAWEI AppGallery?

hi @viperciyes 

Yes. It will fall under below switch case 

 case Source.IS_INSTALLED_FROM_LOCAL_SOURCE:
          // Installed using adb commands or side loading or any cloud service
          source = "Local Source";
          break;

**Comment by viperciyes** [comment]
in this case, can we understand whether the app is downloaded/hacked/installed from local apk or downloaded from appgallery?

**Comment by ravitejaavv** [comment]
Hi @viperciyes 

We can install the apk in multiple ways. Some commonly used ways are

1. adb install <apk-path>
2. Download apk from website and install 
3. Share apk through drive/social/sharing/etc.,
4. From PlayStore/AmazonStore/Other Stores

This plugin detects all above cases where point 1, 2, 3 comes under **Source.IS_INSTALLED_FROM_LOCAL_SOURCE**

**Comment by skripsimu** [comment]
When we download and install apps from Huawei Store, Galaxy store or other, what data will we get? IS_INSTALLED_FROM_OTHER_SOURCE?

**Comment by ravitejaavv** [comment]
> When we download and install apps from Huawei Store, Galaxy store or other, what data will we get? IS_INSTALLED_FROM_OTHER_SOURCE?

Yes. I will review your pull request and merge

**Comment by ravitejaavv** [comment]
Use store_checker: ^1.0.0
