### ISSUE TITLE
"Smart Switch App" identification support

### ISSUE THREAD

**Issue by venzeo** [ravitejaavv/store_checker#8]
Would you please add "Smart Switch App" as a source which is used on Samsung Galaxy phones?
App source:
https://www.samsung.com/us/support/owners/app/smart-switch

**Comment by ravitejaavv** [comment]
Hi @venzeo let me check and get back to you

**Comment by ravitejaavv** [comment]
> Hey @ravitejaavv, is it possible to implement it?

This is available in 1.1.0 version. 

 case Source.IS_INSTALLED_FROM_SAMSUNG_SMART_SWITCH_MOBILE:
          // Installed from Samsung Smart Switch Mobile
          source = "Samsung Smart Switch Mobile";
          break;

**Comment by ravitejaavv** [comment]
> > Hey @ravitejaavv, is it possible to implement it?
> 
> This is available in 1.1.0 version.
> 
> case Source.IS_INSTALLED_FROM_SAMSUNG_SMART_SWITCH_MOBILE: // Installed from Samsung Smart Switch Mobile source = "Samsung Smart Switch Mobile"; break;

Please check and confirm

**Comment by venzeo** [comment]
Superb!
